# Generated by Django 4.2.16 on 2024-09-14 09:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_polygon', models.CharField(max_length=100, verbose_name='Название полигона')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Полигон')),
                ('antimeridian', models.BooleanField(default=False, verbose_name='Aнтимеридиан')),
            ],
            options={
                'verbose_name': 'полигон',
                'verbose_name_plural': 'полигоны',
            },
        ),
    ]
